openapi: 3.0.3
info:
  version: 0.1.0
  title: Differ API Reference
  description: API Endpoints for Differ Application
tags:
  - name: diff
paths:
  /diff:
    get:
      tags:
        - diff
      description: Returns a list of changes
      operationId: diff-get
      responses:
        '200':
          $ref: '#/components/responses/200ResponseDiff'
components:
  schemas:
    ChangeStatus:
      enum: [0, 1, 2, 3]
      x-enum-varnames: [Unchanged, Created, Updated, Deleted]
    DiffModel:
      required:
        - field
        - value
      properties: 
        field:
          oneOf:
            - type: number
            - type: string
        value:
          oneOf:
            - type: integer
            - type: string
            - type: boolean
            - type: array
              items:
                $ref: '#/components/schemas/DiffModel'
        previous:
          anyOf:
            - type: integer
            - type: string
            - type: boolean
        status:
          $ref: '#/components/schemas/ChangeStatus'
  responses: 
    200ResponseDiff:
      description: OK
      content: 
        application/json:
          schema: 
            type: array
            items:
              type: object
              properties:
                username:
                  type: string
                date:
                  type: number
                items:
                  type: array
                  items:
                    $ref: '#/components/schemas/DiffModel'
