/* tslint:disable */
/* eslint-disable */
/**
 * API
 * The main API for all Sandbox apps
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EnumFilterType } from './enum-filter-type';
// May contain unused imports in some cases
// @ts-ignore
import type { FilterTypeValue } from './filter-type-value';

export interface FilterType {
    'value': FilterTypeValue;
    'type': EnumFilterType;
    'field'?: string;
}



