/* tslint:disable */
/* eslint-disable */
/**
 * API
 * The main API for all Sandbox apps
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface LeagueMatchEntity {
    'id': string;
    'groupId': number;
    'matchDate': number;
    'stadium': string;
    'homeTeam': string;
    'awayTeam': string;
    'matchPlayed': boolean;
    'homeTeamScore': number;
    'awayTeamScore': number;
}

