/* tslint:disable */
/* eslint-disable */
/**
 * API
 * The main API for all Sandbox apps
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EnumChangeStatus } from './enum-change-status';
// May contain unused imports in some cases
// @ts-ignore
import type { TreeItemModelField } from './tree-item-model-field';
// May contain unused imports in some cases
// @ts-ignore
import type { TreeItemModelValue } from './tree-item-model-value';

export interface TreeItemModel {
    'field': TreeItemModelField;
    'value': TreeItemModelValue;
    'status'?: EnumChangeStatus;
    'previous'?: TreeItemModel;
}



