/* tslint:disable */
/* eslint-disable */
/**
 * API
 * The main API for all Sandbox apps
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AddressEntity } from './address-entity';

export interface UserEntity {
    'id'?: string;
    'firstName': string;
    'lastName': string;
    'email': string;
    'phone'?: string;
    'birthDate'?: number;
    'gender'?: string;
    'address'?: AddressEntity;
}

