/* tslint:disable */
/* eslint-disable */
/**
 * Differ API Reference
 * API Endpoints for Differ Application
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { RandomGet200Response } from '../models';
/**
 * RandomApi - axios parameter creator
 * @export
 */
export const RandomApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns a list of random names, paginated
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        randomGet: async (page?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/random`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RandomApi - functional programming interface
 * @export
 */
export const RandomApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RandomApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns a list of random names, paginated
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async randomGet(page?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RandomGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.randomGet(page, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * RandomApi - factory interface
 * @export
 */
export const RandomApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RandomApiFp(configuration)
    return {
        /**
         * Returns a list of random names, paginated
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        randomGet(page?: number, options?: any): AxiosPromise<RandomGet200Response> {
            return localVarFp.randomGet(page, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RandomApi - interface
 * @export
 * @interface RandomApi
 */
export interface RandomApiInterface {
    /**
     * Returns a list of random names, paginated
     * @param {number} [page] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RandomApiInterface
     */
    randomGet(page?: number, options?: AxiosRequestConfig): AxiosPromise<RandomGet200Response>;

}

/**
 * RandomApi - object-oriented interface
 * @export
 * @class RandomApi
 * @extends {BaseAPI}
 */
export class RandomApi extends BaseAPI implements RandomApiInterface {
    /**
     * Returns a list of random names, paginated
     * @param {number} [page] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RandomApi
     */
    public randomGet(page?: number, options?: AxiosRequestConfig) {
        return RandomApiFp(this.configuration).randomGet(page, options).then((request) => request(this.axios, this.basePath));
    }
}
