name: Branches
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize
permissions:
  pull-requests: read
jobs:
  validate:
    name: Validate Semantic Title
    runs-on: ubuntu-latest
    steps:
      - name: semantic-pull-request
        uses: amannn/action-semantic-pull-request@v5.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
