name: Branches
on:
  push:
    branches-ignore:
      - main
jobs:
  validate:
    name: Validate Semantic Title
    runs-on: ubuntu-latest
    steps:
      - name: semantic-pull-request
        uses: amannn/action-semantic-pull-request@v5.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
